<?php

namespace AppBundle\Repository;

/**
 * LotsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLots()
    {
        return $this
            ->createQueryBuilder('lots')
            ->join('lots.category', 'category')
            ->where('lots.dateEnd > :curDate')
            ->setParameter('curDate', date('Y-m-d'))
            ->orderBy('lots.id', 'DESC')
            ->setMaxResults(9)
            ->getQuery()
            ->getResult();
    }

    public function findLot($id)
    {
        return $this
            ->createQueryBuilder('lots')
            ->join('lots.category', 'category')
            ->where('lots.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getArrayResult();
    }

    public function findAllLots($id)
    {
        return $this
            ->createQueryBuilder('lots')
            ->join('lots.category', 'category')
            ->where('category.id = :id')
            ->andWhere('lots.dateEnd > :curDate')
            ->setParameter('id', $id)
            ->setParameter('curDate', date('Y-m-d'))
            ->orderBy('lots.id', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function findSearch($search)
    {
        return $this
            ->createQueryBuilder('lots')
            ->join('lots.category', 'category')
            ->where($this->createQueryBuilder('lots')->expr()->like('lots.name', ':search'))
            ->andWhere('lots.dateEnd > :curDate')
//            ->where($this->createQueryBuilder('lots')->expr()->like($this->createQueryBuilder('lots')->expr()->lower('lots.name'), ($this->createQueryBuilder('lots')->expr())->lower(':search')))
//            ->where('lots.name = :search')
            ->setParameter('search', $search)
            ->setParameter('curDate', date('Y-m-d'))
            ->getQuery()
            ->getResult();
    }
}
