<?php

namespace AppBundle\Repository;

/**
 * LotsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLots()
    {
        return $this
            ->createQueryBuilder('lots')
            ->join('lots.category', 'category')
            ->orderBy('lots.id', 'DESC')
            ->setMaxResults(9)
            ->getQuery()
            ->getResult();
    }
}
