<?php

namespace AppBundle\Repository;

/**
 * RatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRates($id)
    {
        return $this
            ->createQueryBuilder('rates')
            ->join('rates.lot', 'lots')
            ->where('lots.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }
}
