# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Users: bcrypt
#            algorithm: bcrypt
#    encoders:
#        Symfony\Component\Security\Core\Users: sha512
#        App\Entity\Users:
#            algorithm:  bcrypt
#            cost: 12

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        my_provider:
            entity:
                class: AppBundle\Entity\Users
                property: email
#        in_memory:
#            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#            pattern:    ^/
            # http_basic: ~
#            provider: our_db_provider

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
                provider: my_provider

            logout:
                path: /logout
                target: /

    access_control:
        # потребовать ROLE_USER для /addLot*
        - { path: ^/addLot, roles: ROLE_USER }
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
